import ClientProvider from '@src/components/providers/main';
import '@src/styles/globals.css';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Be_Vietnam_Pro } from 'next/font/google';

const beFont = Be_Vietnam_Pro({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin', 'vietnamese'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={`${beFont.className} h-full antialiased`}
            data-scroll-behavior='smooth'
        >
            <body suppressHydrationWarning>
                <NextIntlClientProvider>
                    <ClientProvider>{children}</ClientProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
